"use client";

import Link from "next/link";
import ProjectMedia from "@/components/ProjectMedia";
import ContentGrid from "@/components/ContentGrid";
import OtherProjects from "@/components/OtherProjects";
import { useLanguage } from "@/lib/LanguageContext";

const robotos = (file: string) => `/design/robotos/${file}`;

function FullRow({ src }: { src: string }) {
  return (
    <div className="grid items-center grid-cols-1 md:grid-cols-6">
      <div className="md:col-start-2 md:col-span-4">
        <ProjectMedia src={src} alt="Robotos" />
      </div>
    </div>
  );
}

function EdgeRow({ items }: { items: string[] }) {
  return (
    <div
      className={`grid items-center grid-cols-1 gap-4 ${
        items.length === 2
          ? "md:grid-cols-2"
          : items.length === 3
          ? "md:grid-cols-3"
          : "md:grid-cols-4"
      }`}
    >
      {items.map((src) => (
        <ProjectMedia key={src} src={src} alt="Robotos" />
      ))}
    </div>
  );
}

const socialGrid = [16, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 28].map((n) =>
  robotos(`${n}_Robotos.mp4`)
);

export default function Project13() {
  const { language } = useLanguage();
  const isEs = language === "es";

  return (
    <ContentGrid className="pb-16 flex flex-col gap-10">
      <div className="flex flex-col gap-4 pt-6">
        <Link href="/home" className="flex items-center gap-2 text-sm opacity-70 hover:opacity-100 transition-opacity w-fit">
          {isEs ? "← Volver" : "← Back"}
        </Link>
        <div className="flex items-baseline gap-3 flex-wrap">
          <h1 className="text-2xl">Robotos</h1>
          <span className="text-sm text-black/60">{isEs ? "2021–2024 · Brand | Ilustración" : "2021–2024 · Brand | Illustration"}</span>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 text-black/70">
          <p>
            {isEs ? (
              <>
                Colección de Arte NFT que vive en la blockchain, generados algorítmicamente. Robopets surge
                de Robotos y la creé en colaboración con Pablo Stanley — cientos de bocetos, cientos de
                ideas, cientos de risas dieron más de 8,000 PFPs que adquirieron más de 4,000 personas,
                teniendo un volumen de intercambio de la colección de más de 890 Ethereum.
                <br />
                <br />
                Estábamos en pleno boom de los NFTs, así que se sentía urgencia en todos los sentidos —
                necesitábamos crear la colección lo antes posible. El proceso de diseño tomó alrededor de
                solo 2 semanas (una locura).
              </>
            ) : (
              "Robotos NFTs is an art project that emerged in 2021 during the digital art NFT boom, created by Pablo Stanley and other collaborators — it's a collection of 10,000 unique characters generated by an algorithm."
            )}
          </p>
          <p>
            {isEs
              ? "Al ser los Robopets mascotas de los Robotos, el reto era darles una identidad compartida entre sí, pero que cada pet también tuviera rasgos únicos. La solución: cada Robopet tendría por lo menos un rasgo del Roboto — ya sea su color de cuerpo, ojos, casco u otro, logrando así una conexión real entre cada Roboto y su mascota. Siempre tuvimos en mente que estos elementos serían la base para crear mundos y contenidos para la marca."
              : "The art was created by Pablo Stanley — heads, bodies, eyes, mouths… the algorithm took care of placing them randomly so every character came out unique."}
          </p>
        </div>
      </div>

      <FullRow src={robotos("7_Robotos.gif")} />

      <ProjectMedia src={robotos("1_Robotos.webp")} alt="Robotos" />

      <div className="grid items-center grid-cols-1 md:grid-cols-6">
        <div className="md:col-start-2 md:col-span-4 grid items-center grid-cols-1 md:grid-cols-2 gap-4">
          <ProjectMedia src={robotos("19_Robotos.mp4")} alt="Robotos" />
          <ProjectMedia src={robotos("31_Robotos.mp4")} alt="Robotos" />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 text-black/70">
        <div>
          <h2 className="font-bold text-black mb-2">{isEs ? "Mi aporte" : "My contribution"}</h2>
          <p>
            {isEs ? (
              <>
                Fue increíble poder aplicar un sistema de diseño en ilustraciones.
                El proceso siempre empezaba a mano, se creó la base de diferentes pets
                (perrito, gatito, etc..) sobre esas bases comenzamos a idear elementos que 
                sería divertido que tuvieran, sin olvidar elementos con los que ya contaban 
                los Robotos.
              </>
            ) : (
              <>
                I joined the project just a few weeks after it started; my main role was creating
                design systems with illustrations, which even led us to create a new collection,
                &quot;Robopets,&quot; the little pets belonging to the Robotos.
              </>
            )}
          </p>
          <p className="mt-4">
            {isEs
              ? "Tuvimos muchas juntas para definir qué rasgos funcionaban y cuáles no. La comunidad fue una parte importante del proceso, y Pablo y yo nos inspiramos de ahí."
              : "On Robopets my role was to keep track of the new assets being added to the collection and make sure they matched their Roboto. It was a lot of fun having the brainstorming sessions, sketching, and final vectorization of all the new elements — very satisfying to see all the new Robopets owners keeping their Robotos company"}
          </p>
        </div>
        <p>
          {isEs
            ? "Al final fue muy satisfactorio ver a todos los nuevos dueños de Robopets haciendo compañía a sus Robotos."
            : "In my role on the project I handled branding topics in parallel, creating visuals and providing usage guidelines. I put my motion graphics skills to work, building small design systems."}
        </p>
      </div>

      <div className="flex flex-col gap-4">
        <EdgeRow items={[robotos("18_Robotos.mp4"), robotos("17_Robotos.mp4")]} />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 text-black/70 text-sm">
          <p>{isEs ? "Contenido para el anuncio de Robopets" : "Content for the Robopets announcement"}</p>
          <p>{isEs ? "La colección en un billboard en NY." : "The collection on a billboard in NY."}</p>
        </div>
      </div>

      <div className="flex flex-col gap-4">
        <div className="grid items-center grid-cols-1 md:grid-cols-4 gap-0">
          <ProjectMedia src={robotos("2_Robotos.mp4")} alt="Robotos" />
          <ProjectMedia src={robotos("3_Robotos.mp4")} alt="Robotos" />
          <ProjectMedia src={robotos("4_Robotos.mp4")} alt="Robotos" />
          <ProjectMedia src={robotos("5_Robotos.mp4")} alt="Robotos" />
        </div>
        <p className="text-sm text-black/70">
          {isEs
            ? "Los personajes salieron de la pantalla y junto con el equipo, los plasmamos en pared."
            : "The characters stepped out of the screen and, together with the team, we brought them to a wall."}
        </p>
      </div>

      <EdgeRow items={[robotos("9_Robotos.jpg"), robotos("10_Robotos.jpg"), robotos("6_Robotos.jpg")]} />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 text-black/70">
        <div>
          <h2 className="font-bold text-black mb-2">{isEs ? "Colaboradores" : "Collaborators"}</h2>
          <p>
            {isEs
              ? "En ese periodo fuimos una de las principales colecciones de NFTs a nivel mundial, uno de los logros más tops del cual me sentí muy orgulloso fue ver uno de nuestros Robotos en un comercial de X (antes Twitter) cuando se implementaban los PFP de las colecciones de NFTs, codeandonos con colecciones como Bored Apes, Cryptopunks, Cool Cats, entre otros."
              : "I worked very closely with Pablo Stanley, the project's creator, as well as with Mariana Pedroza, Viri, Rojo, Zack, Gabs, Sjoerd, Niklas, and others."}
          </p>
        </div>
        <p>
          {isEs
            ? "Gracias a este proyecto logré ampliar mi panorama a nivel profesional y personal, tuve oportunidades de salir de México y conocer países como Francia (donde por cierto, montamos una galería de arte express, una experiencia increíble). También desarrollé mi skill de crear sistemas de diseño ampliamente escalables mas allá de una interfaz WEB, fue un buen reto para mi, salir más allá de las UI, botones, cards y esas cosas."
            : "We were in the middle of the NFT boom, so there was a sense of urgency in every aspect — what we made one day already felt old the next, and at the same time it was challenging to learn new technologies and try to implement them into our product. This was where I started to see the potential of AI."}
        </p>
      </div>

      <div className="flex flex-col gap-4">
        <FullRow src={robotos("8_Robotos.gif")} />
        <p className="text-sm text-black/70">{isEs ? "Sistema de diseño para Social Media." : "Design system for Social Media."}</p>
      </div>

      <EdgeRow items={[robotos("15_Robotos.mp4"), robotos("14_Robotos.mp4")]} />

      <div className="flex flex-col gap-4">
        <div className="grid items-center grid-cols-2 md:grid-cols-4 gap-4">
          {socialGrid.map((src) => (
            <ProjectMedia key={src} src={src} alt="Robotos" />
          ))}
        </div>
        <p className="text-sm text-black/70">
          {isEs ? "ilustraciones animadas para contenido de Social Media." : "Animated illustrations for Social Media content."}
        </p>
      </div>

      <div className="flex flex-col gap-4">
        <EdgeRow items={[robotos("11_Robotos.mp4"), robotos("12_Robotos.mp4")]} />
        <p className="text-sm text-black/70">
          {isEs ? "Sistema de diseño para trajes y fondos intercambiables" : "Design system for interchangeable outfits and backgrounds"}
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 text-black/70">
        <div>
          <h2 className="font-bold text-black mb-2">{isEs ? "Yo en Robotos" : "Result"}</h2>
          <p>
            {isEs
              ? "Además de la colección de los Robopets mi participación en el proyecto fue encaminada a temas de branding, creando visuales y dando guías de uso. Jugué con mis skills de motions graphics e hice pequeños sistemas de diseño."
              : "My involvement over those couple of years left behind a new NFT collection, close to 9,000 new items, as well as an amplified visual line for on/off-line media, and a wide repertoire of animations and illustrations."}
          </p>

          <p>
            {isEs
              ? "Mi participación durante ese par de años dejó una colección nueva de NFTs (Robopets), cerca de 9,000 items creados, una línea visual amplificada para medios on/off line y un amplio repertorio de animaciones e ilustraciones."
              : "My involvement over those couple of years left behind a new NFT collection, close to 9,000 new items, as well as an amplified visual line for on/off-line media, and a wide repertoire of animations and illustrations."}
          </p>
  
        </div>
        <div>
          <h2 className="font-bold text-black mb-2">{isEs ? "Aprendizaje" : "Learnings"}</h2>
          <p>
            {isEs
              ? "Trabajé muy de cerca con Pablo Stanley, creador del proyecto. Así como con Mariana Pedroza, Viri, Rojo, Zack, Gabs, Sjoerd, Niklas y otros."
              : "Thanks to this project I was able to broaden my horizons professionally and personally — I had opportunities to leave Mexico and visit other countries like France (where, by the way, we set up an express art gallery, an incredible experience). I also developed my skill in creating widely scalable design systems — it was a good challenge for me, going beyond UI, buttons, cards, and those kinds of things."}
          </p>
          <p className="mt-4">
            X (
            <a href="https://x.com/robotosNFT" target="_blank" rel="noreferrer" className="underline underline-offset-4">
              https://x.com/robotosNFT
            </a>
            )
            <br />
            WEB (
            <a href="https://www.robotos.art/" target="_blank" rel="noreferrer" className="underline underline-offset-4">
              https://www.robotos.art/
            </a>
            )
            <br />
            {isEs ? "Open Sea Robotos (" : "OpenSea Robotos ("}
            <a
              href="https://opensea.io/es/collection/robotos-official"
              target="_blank"
              rel="noreferrer"
              className="underline underline-offset-4"
            >
              https://opensea.io/es/collection/robotos-official
            </a>
            )
            <br />
            {isEs ? "Open Sea Robopets (" : "OpenSea Robopets ("}
            <a
              href="https://opensea.io/es/collection/robopets"
              target="_blank"
              rel="noreferrer"
              className="underline underline-offset-4"
            >
              https://opensea.io/es/collection/robopets
            </a>
            )
          </p>
        </div>
      </div>

      <OtherProjects currentHref="/project13" />
    </ContentGrid>
  );
}
