"use client";

import Link from "next/link";
import ProjectMedia from "@/components/ProjectMedia";
import ContentGrid from "@/components/ContentGrid";
import OtherProjects from "@/components/OtherProjects";
import { useLanguage } from "@/lib/LanguageContext";

const robotos = (file: string) => `/design/robotos/${file}`;

function FullRow({ src }: { src: string }) {
  return (
    <div className="grid items-center grid-cols-1 md:grid-cols-6">
      <div className="md:col-start-2 md:col-span-4">
        <ProjectMedia src={src} alt="Robotos" />
      </div>
    </div>
  );
}

function EdgeRow({ items }: { items: string[] }) {
  return (
    <div
      className={`grid items-center grid-cols-1 gap-4 ${
        items.length === 2
          ? "md:grid-cols-2"
          : items.length === 3
          ? "md:grid-cols-3"
          : "md:grid-cols-4"
      }`}
    >
      {items.map((src) => (
        <ProjectMedia key={src} src={src} alt="Robotos" />
      ))}
    </div>
  );
}

const socialGrid = [16, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 28].map((n) =>
  robotos(`${n}_Robotos.mp4`)
);

export default function Project13() {
  const { language } = useLanguage();
  const isEs = language === "es";

  return (
    <ContentGrid className="pb-16 flex flex-col gap-10">
      <div className="flex flex-col gap-4 pt-6">
        <Link href="/home" className="flex items-center gap-2 text-sm opacity-70 hover:opacity-100 transition-opacity w-fit">
          {isEs ? "← Volver" : "← Back"}
        </Link>
        <div className="flex items-baseline gap-3 flex-wrap">
          <h1 className="text-2xl">Robotos</h1>
          <span className="text-sm text-black/60">{isEs ? "2021–2024 · Brand | Ilustración" : "2021–2024 · Brand | Illustration"}</span>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 text-black/70">
          <p>
            {isEs
              ? "Robotos NFTs es un proyecto se arte que surgio en el 2021 en el boom del arte digital NFT, fué creado por Pablo Stanley y otros colaboradores, es una colección de 10,000 personajes unicos que fueron generados mediante un algoritmo."
              : "Robotos NFTs is an art project that emerged in 2021 during the digital art NFT boom, created by Pablo Stanley and other collaborators — it's a collection of 10,000 unique characters generated by an algorithm."}
          </p>
          <p>
            {isEs
              ? "El arte fue realizado por Pablo Stanley, cabezas, cuerpos, ojos, bocas… el algoritmo se encargo de colocarlos de forma aleatoria para lograr que cada personaje fuera único."
              : "The art was created by Pablo Stanley — heads, bodies, eyes, mouths… the algorithm took care of placing them randomly so every character came out unique."}
          </p>
        </div>
      </div>

      <FullRow src={robotos("7_Robotos.gif")} />

      <ProjectMedia src={robotos("1_Robotos.webp")} alt="Robotos" />

      <div className="grid items-center grid-cols-1 md:grid-cols-6">
        <div className="md:col-start-2 md:col-span-4 grid items-center grid-cols-1 md:grid-cols-2 gap-4">
          <ProjectMedia src={robotos("19_Robotos.mp4")} alt="Robotos" />
          <ProjectMedia src={robotos("31_Robotos.mp4")} alt="Robotos" />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 text-black/70">
        <div>
          <h2 className="font-bold text-black mb-2">{isEs ? "Mi aporte" : "My contribution"}</h2>
          <p>
            {isEs ? (
              <>
                Me subí al proyecto justo una semanas despues de haber iniciado, mi roll principal
                fue crear sistemas de diseño con ilustraciones, que incluso nos llevaron a crear una
                colección nueva &quot;Robopets&quot; que son las pequeñas mascotas de los Robotos.
              </>
            ) : (
              <>
                I joined the project just a few weeks after it started; my main role was creating
                design systems with illustrations, which even led us to create a new collection,
                &quot;Robopets,&quot; the little pets belonging to the Robotos.
              </>
            )}
          </p>
          <p className="mt-4">
            {isEs
              ? "En los Robopets mi roll fue llevar el control de los nuevos assets que se sumarían a la colección e hicieran match con su Roboto. Fue muy divertido tener las sesiones de brainstorm, bocetaje y vectorización final de todos los nuevos elementos, muy satisfactorio ver a todos los nuevos dueños de Robopets haciendo compañia a sus Robotos"
              : "On Robopets my role was to keep track of the new assets being added to the collection and make sure they matched their Roboto. It was a lot of fun having the brainstorming sessions, sketching, and final vectorization of all the new elements — very satisfying to see all the new Robopets owners keeping their Robotos company"}
          </p>
        </div>
        <p>
          {isEs
            ? "En mi participacion en el proyecto lleve a la par temas de branding, creando visuales y dando guías de uso. Jugué con mis skills de motions graphics, haciendo pequeños sistemas de diseño."
            : "In my role on the project I handled branding topics in parallel, creating visuals and providing usage guidelines. I put my motion graphics skills to work, building small design systems."}
        </p>
      </div>

      <div className="flex flex-col gap-4">
        <EdgeRow items={[robotos("18_Robotos.mp4"), robotos("17_Robotos.mp4")]} />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 text-black/70 text-sm">
          <p>{isEs ? "Contenido para el anuncio de Robopets" : "Content for the Robopets announcement"}</p>
          <p>{isEs ? "La colección en un billboard en NY." : "The collection on a billboard in NY."}</p>
        </div>
      </div>

      <div className="flex flex-col gap-4">
        <div className="grid items-center grid-cols-1 md:grid-cols-4 gap-0">
          <ProjectMedia src={robotos("2_Robotos.mp4")} alt="Robotos" />
          <ProjectMedia src={robotos("3_Robotos.mp4")} alt="Robotos" />
          <ProjectMedia src={robotos("4_Robotos.mp4")} alt="Robotos" />
          <ProjectMedia src={robotos("5_Robotos.mp4")} alt="Robotos" />
        </div>
        <p className="text-sm text-black/70">
          {isEs
            ? "Los personajes salieron de la pantalla y junto con el equipo, los plasmamos en pared."
            : "The characters stepped out of the screen and, together with the team, we brought them to a wall."}
        </p>
      </div>

      <EdgeRow items={[robotos("9_Robotos.jpg"), robotos("10_Robotos.jpg"), robotos("6_Robotos.jpg")]} />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 text-black/70">
        <div>
          <h2 className="font-bold text-black mb-2">{isEs ? "Colaboradores" : "Collaborators"}</h2>
          <p>
            {isEs
              ? "Trabajé muy de cerca con Pablo Stanley, creador del proyecto. Así como con Mariana Pedroza, Viri, Rojo, Zack, Gabs, Sjoerd, Niklas y otros."
              : "I worked very closely with Pablo Stanley, the project's creator, as well as with Mariana Pedroza, Viri, Rojo, Zack, Gabs, Sjoerd, Niklas, and others."}
          </p>
          <h2 className="font-bold text-black mt-4 mb-2">{isEs ? "Objetivo" : "Goal"}</h2>
          <p>
            {isEs
              ? "Crear un sistema de diseño de ilustraciones faciles de escalar para crear mas personajes, más mundos y más contenido en general."
              : "Create an illustration design system that's easy to scale to make more characters, more worlds, and more content in general."}
          </p>
          <p className="mt-4">
            {isEs
              ? "Ampliar la difusión de la marca, off/on line, justo para eso fui un brand guardian Roboto."
              : "Expand the brand's reach, off/on line — that's exactly what I was there for, as a Roboto brand guardian."}
          </p>
        </div>
        <p>
          {isEs
            ? "Estábamos en el boom de los NFTS por lo que se siente un sentido de urgencia en todos los aspectos, se sentia que lo que haciamos ese día, al siguiente ya era algo viejo y a la vez retador el conocer nuevas tecnologías y buscar implementarlas a nuestro producto, aqui fue donde comencé a ver el potencial de la AI."
            : "We were in the middle of the NFT boom, so there was a sense of urgency in every aspect — what we made one day already felt old the next, and at the same time it was challenging to learn new technologies and try to implement them into our product. This was where I started to see the potential of AI."}
        </p>
      </div>

      <div className="flex flex-col gap-4">
        <FullRow src={robotos("8_Robotos.gif")} />
        <p className="text-sm text-black/70">{isEs ? "Sistema de diseño para Social Media." : "Design system for Social Media."}</p>
      </div>

      <EdgeRow items={[robotos("15_Robotos.mp4"), robotos("14_Robotos.mp4")]} />

      <div className="flex flex-col gap-4">
        <div className="grid items-center grid-cols-2 md:grid-cols-4 gap-4">
          {socialGrid.map((src) => (
            <ProjectMedia key={src} src={src} alt="Robotos" />
          ))}
        </div>
        <p className="text-sm text-black/70">
          {isEs ? "ilustraciones animadas para contenido de Social Media." : "Animated illustrations for Social Media content."}
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 text-black/70">
        <div>
          <h2 className="font-bold text-black mb-2">{isEs ? "Proceso" : "Process"}</h2>
          <p>
            {isEs
              ? "Juntabamos los conceptos que debía tener el mundo de los Robotos, a partir de ahi, todo nuestro contenido visual tendría que tener por lo menos un pilar de estos concepto, por ejemplo, la amistad, un Roboto podría aparecer jugando con otro Roboto."
              : "We gathered the concepts the Robotos world needed to have; from there, all our visual content had to include at least one pillar from these concepts — for example, friendship, where a Roboto might appear playing with another Roboto."}
          </p>
        </div>
        <p>
          {isEs ? (
            <>
              A la hora de bocetar, siempre era bueno tener una sesión con Pablo para dar double
              check sobre si ese es el mensaje a futuro que queriamos dar, afortunadamente casi
              siempre era &quot;tsssss, justo era eso, dude haha&quot;
            </>
          ) : (
            <>
              When it came time to sketch, it was always good to have a session with Pablo to
              double-check whether that was the message we wanted to convey going forward —
              fortunately, it was almost always &quot;tsssss, that&apos;s exactly it, dude
              haha&quot;
            </>
          )}
        </p>
      </div>

      <div className="flex flex-col gap-4">
        <EdgeRow items={[robotos("11_Robotos.mp4"), robotos("12_Robotos.mp4")]} />
        <p className="text-sm text-black/70">
          {isEs ? "Sistema de diseño para trajes y fondos intercambiables" : "Design system for interchangeable outfits and backgrounds"}
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 text-black/70">
        <div>
          <h2 className="font-bold text-black mb-2">{isEs ? "Resultado" : "Result"}</h2>
          <p>
            {isEs
              ? "Mi participación durante ese par de años se dejo una colección nueva de ntfs, cerca de 9,000 items nuevos, tambien una linea visual amplificada para medios on/off line, un amplio repertorio de animaciones e ilustraciones."
              : "My involvement over those couple of years left behind a new NFT collection, close to 9,000 new items, as well as an amplified visual line for on/off-line media, and a wide repertoire of animations and illustrations."}
          </p>
          <p className="mt-4">
            {isEs
              ? "En ese periodo fuimos una de las principales colecciones de NFTs a nivel mundial, uno de los logros mas tops que me sentí muy orgulloso de formar parte fue ver uno de nuestros Robotos en un comercial de X donde se implementaban los PFP de las colecciones de NFTs, codeandonos con dcolecciones como Bored Apes, Cyberpunks, Cool Cats, entre otros."
              : "During that period we were one of the world's leading NFT collections; one of the top achievements I felt very proud to be part of was seeing one of our Robotos in an X commercial featuring PFPs from NFT collections, rubbing shoulders with collections like Bored Apes, Cryptopunks, Cool Cats, and others."}
          </p>
        </div>
        <div>
          <h2 className="font-bold text-black mb-2">{isEs ? "Aprendizaje" : "Learnings"}</h2>
          <p>
            {isEs
              ? "Gracias a este proyecto logré ampliar mi panorama a nivel profesional y personal, tuve oportunidades de salir de México y conocer otros paises como Francia (donde por cierto, montamos una galeria de arte express, una experiencia increible). Tambien desarrolle mi skill de crear sistemas de diseño ampliamente escalables, fue un buen reto para mi, salir más allá de las UI, botones, cards y esas cosas."
              : "Thanks to this project I was able to broaden my horizons professionally and personally — I had opportunities to leave Mexico and visit other countries like France (where, by the way, we set up an express art gallery, an incredible experience). I also developed my skill in creating widely scalable design systems — it was a good challenge for me, going beyond UI, buttons, cards, and those kinds of things."}
          </p>
          <p className="mt-4">
            X (
            <a href="https://x.com/robotosNFT" target="_blank" rel="noreferrer" className="underline underline-offset-4">
              https://x.com/robotosNFT
            </a>
            )
            <br />
            WEB (
            <a href="https://www.robotos.art/" target="_blank" rel="noreferrer" className="underline underline-offset-4">
              https://www.robotos.art/
            </a>
            )
            <br />
            {isEs ? "Open Sea Robotos (" : "OpenSea Robotos ("}
            <a
              href="https://opensea.io/es/collection/robotos-official"
              target="_blank"
              rel="noreferrer"
              className="underline underline-offset-4"
            >
              https://opensea.io/es/collection/robotos-official
            </a>
            )
            <br />
            {isEs ? "Open Sea Robopets (" : "OpenSea Robopets ("}
            <a
              href="https://opensea.io/es/collection/robopets"
              target="_blank"
              rel="noreferrer"
              className="underline underline-offset-4"
            >
              https://opensea.io/es/collection/robopets
            </a>
            )
          </p>
        </div>
      </div>

      <OtherProjects currentHref="/project13" />
    </ContentGrid>
  );
}
